name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust toolchain
      run:
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --component llvm-tools-preview
    - name: Install grcov
      run: cargo install grcov
    - name: Build
      run: cargo build --verbose
      env:
        RUSTFLAGS: -Cinstrument-coverage
    - name: Run tests
      run: cargo test --verbose
      env:
        RUSTFLAGS: -Cinstrument-coverage
    - name: Process coverage data
      run: grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
    - uses: codecov/codecov-action@v4
      with:
        files: ./lcov.info
        token: ${{ secrets.CODECOV_TOKEN }}
